export const ACTIVITY_CREATE_REQUEST = "ACTIVITY_CREATE_REQUEST";
export const ACTIVITY_CREATE_SUCCESS = "ACTIVITY_CREATE_SUCCESS";
export const ACTIVITY_CREATE_FAIL = "ACTIVITY_CREATE_FAIL";

export const ACTIVITY_LIST_REQUEST = "ACTIVITY_LIST_REQUEST";
export const ACTIVITY_LIST_SUCCESS = "ACTIVITY_LIST_SUCCESS";
export const ACTIVITY_LIST_FAIL = "ACTIVITY_LIST_FAIL";