export const ALERT_LIST_REQUEST = "ALERT_LIST_REQUEST";
export const ALERT_LIST_SUCCESS = "ALERT_LIST_SUCCESS";
export const ALERT_LIST_FAIL = "ALERT_LIST_FAIL";

export const ALERT_UPDATE_REQUEST = "ALERT_UPDATE_REQUEST";
export const ALERT_UPDATE_SUCCESS = "ALERT_UPDATE_SUCCESS";
export const ALERT_UPDATE_FAIL = "ALERT_UPDATE_FAIL";