export const ALERT_LIST_REQUEST = "ALERT_LIST_REQUEST";
export const ALERT_LIST_SUCCESS = "ALERT_LIST_SUCCESS";
export const ALERT_LIST_FAIL = "ALERT_LIST_FAIL";

export const ALERT_UPDATE_REQUEST = "ALERT_UPDATE_REQUEST";
export const ALERT_UPDATE_SUCCESS = "ALERT_UPDATE_SUCCESS";
export const ALERT_UPDATE_FAIL = "ALERT_UPDATE_FAIL";

export const ALERT_CREATE_REQUEST = "ALERT_CREATE_REQUEST";
export const ALERT_CREATE_SUCCESS = "ALERT_CREATE_SUCCESS";
export const ALERT_CREATE_FAIL = "ALERT_CREATE_FAIL";

export const ALERT_DELETE_REQUEST = "ALERT_DELETE_REQUEST";
export const ALERT_DELETE_SUCCESS = "ALERT_DELETE_SUCCESS";
export const ALERT_DELETE_FAIL = "ALERT_DELETE_FAIL";

export const TYPE_ALERT_LIST_REQUEST = "TYPE_ALERT_LIST_REQUEST";
export const TYPE_ALERT_LIST_SUCCESS = "TYPE_ALERT_LIST_SUCCESS";
export const TYPE_ALERT_LIST_FAIL = "TYPE_ALERT_LIST_FAIL";