export const ENTRY_CREATE_REQUEST = 'ENTRY_CREATE_REQUEST';
export const ENTRY_CREATE_SUCCESS = 'ENTRY_CREATE_SUCCESS';
export const ENTRY_CREATE_FAIL = 'ENTRY_CREATE_FAIL';

export const ENTRY_GET_REQUEST = 'ENTRY_GET_REQUEST';
export const ENTRY_GET_SUCCESS = 'ENTRY_GET_SUCCESS';
export const ENTRY_GET_FAIL = 'ENTRY_GET_FAIL';