export const EXPENSE_LIST_REQUEST = 'EXPENSE_LIST_REQUEST';
export const EXPENSE_LIST_SUCCESS = 'EXPENSE_LIST_SUCCESS';
export const EXPENSE_LIST_FAIL = 'EXPENSE_LIST_FAIL';

export const EXPENSE_LIST_BY_DATE_REQUEST = 'EXPENSE_LIST_BY_DATE_REQUEST';
export const EXPENSE_LIST_BY_DATE_SUCCESS = 'EXPENSE_LIST_BY_DATE_SUCCESS';
export const EXPENSE_LIST_BY_DATE_FAIL = 'EXPENSE_LIST_BY_DATE_FAIL';

export const EXP_LIST_REQUEST = 'EXP_LIST_REQUEST';
export const EXP_LIST_SUCCESS = 'EXP_LIST_SUCCESS';
export const EXP_LIST_FAIL = 'EXP_LIST_FAIL';

export const EXPENSE_CREATE_REQUEST = 'EXPENSE_CREATE_REQUEST';
export const EXPENSE_CREATE_SUCCESS = 'EXPENSE_CREATE_SUCCESS';
export const EXPENSE_CREATE_FAIL = 'EXPENSE_CREATE_FAIL';

export const EXPENSE_DELETE_REQUEST = 'EXPENSE_DELETE_REQUEST';
export const EXPENSE_DELETE_SUCCESS = 'EXPENSE_DELETE_SUCCESS';
export const EXPENSE_DELETE_FAIL = 'EXPENSE_DELETE_FAIL';