export const NEXT_EXPENSE_CREATE_REQUEST = 'NEXT_EXPENSE_CREATE_REQUEST';
export const NEXT_EXPENSE_CREATE_SUCCESS = 'NEXT_EXPENSE_CREATE_SUCCESS';
export const NEXT_EXPENSE_CREATE_FAIL = 'NEXT_EXPENSE_CREATE_FAIL';

export const NEXT_EXPENSE_GET_REQUEST = 'NEXT_EXPENSE_GET_REQUEST';
export const NEXT_EXPENSE_GET_SUCCESS = 'NEXT_EXPENSE_GET_SUCCESS';
export const NEXT_EXPENSE_GET_FAIL = 'NEXT_EXPENSE_GET_FAIL';

export const NEXT_EXPENSE_UPDATE_REQUEST = 'NEXT_EXPENSE_UPDATE_REQUEST';
export const NEXT_EXPENSE_UPDATE_SUCCESS = 'NEXT_EXPENSE_UPDATE_SUCCESS';
export const NEXT_EXPENSE_UPDATE_FAIL = 'NEXT_EXPENSE_UPDATE_FAIL';