export const ROUTINES_GET_REQUEST = "ROUTINES_GET_REQUEST";
export const ROUTINES_GET_SUCCESS = "ROUTINES_GET_SUCCESS";
export const ROUTINES_GET_FAIL = "ROUTINES_GET_FAIL";

export const ROUTINES_CREATE_REQUEST = "ROUTINES_CREATE_REQUEST";
export const ROUTINES_CREATE_SUCCESS = "ROUTINES_CREATE_SUCCESS";
export const ROUTINES_CREATE_FAIL = "ROUTINES_CREATE_FAIL";
