export const USER_SIGIN_REQUEST = "USER_SIGIN_REQUEST";
export const USER_SIGIN_SUCCESS = "USER_SIGIN_SUCCESS";
export const USER_SIGIN_FAIL = "USER_SIGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_SUSCRIBE_REQUEST = "USER_SUSCRIBE_REQUEST";
export const USER_SUSCRIBE_SUCCESS = "USER_SUSCRIBE_SUCCESS";
export const USER_SUSCRIBE_FAIL = "USER_SUSCRIBE_FAIL";

export const USER_SIGNOUT_FAIL = "USER_SIGNOUT_FAIL";

export const PUBLIC_VAPID_KEY = "BDDk3ILb3FjIjAvTs9PWMoObhChnrBUYwHAsdplom7fePD36G6ZFJumGgSe6C4M3pOpYvFb38XX2wJRIN4B6V_0";
