export const GET_MONTHS_REQUEST = "GET_MONTHS_REQUEST";
export const GET_MONTHS_SUCCESS = "GET_MONTHS_SUCCESS";
export const GET_MONTHS_FAIL = "GET_MONTHS_FAIL";

export const SET_MONTH_REQUEST = "SET_MONTH_REQUEST";
export const SET_MONTH_SUCCESS = "SET_MONTH_SUCCESS";
export const SET_MONTH_FAIL = "SET_MONTH_FAIL";

export const SET_YEAR_REQUEST = "SET_YEAR_REQUEST";
export const SET_YEAR_SUCCESS = "SET_YEAR_SUCCESS";
export const SET_YEAR_FAIL = "SET_YEAR_FAIL";

export const SET_VIEWER_REQUEST = "SET_VIEWER_REQUEST";
export const SET_VIEWER_SUCCESS = "SET_VIEWER_SUCCESS";
export const SET_VIEWER_FAIL = "SET_VIEWER_FAIL";

export const SET_NOTIFICATIONS_REQUEST = "SET_NOTIFICATIONS_REQUEST";
export const SET_NOTIFICATIONS_SUCCESS = "SET_NOTIFICATIONS_SUCCESS";
export const SET_NOTIFICATIONS_FAIL = "SET_NOTIFICATIONS_FAIL";

export const SET_GROUP_REQUEST = "SET_GROUP_REQUEST";
export const SET_GROUP_SUCCESS = "SET_GROUP_SUCCESS";
export const SET_GROUP_FAIL = "SET_GROUP_FAIL";