export const GET_MONTHS_REQUEST = "GET_MONTHS_REQUEST";
export const GET_MONTHS_SUCCESS = "GET_MONTHS_SUCCESS";
export const GET_MONTHS_FAIL = "GET_MONTHS_FAIL";

export const SET_NOTIFICATIONS_REQUEST = "SET_NOTIFICATIONS_REQUEST";
export const SET_NOTIFICATIONS_SUCCESS = "SET_NOTIFICATIONS_SUCCESS";
export const SET_NOTIFICATIONS_FAIL = "SET_NOTIFICATIONS_FAIL";

export const SET_FILTERS_REQUEST = "SET_FILTERS_REQUEST";
export const SET_FILTERS_SUCCESS = "SET_FILTERS_SUCCESS";
export const SET_FILTERS_FAIL = "SET_FILTERS_FAIL";